export type SupportedRegion = { code: string; name: string; aliases?: readonly string[] };

// 국토교통부 LAWD_CD (법정동코드 앞 5자리). The first release covers the
// metropolitan areas where district-level apartment searches are most common.
export const SUPPORTED_REGIONS: readonly SupportedRegion[] = [
  { code: "11110", name: "서울특별시 종로구", aliases: ["서울 종로구"] },
  { code: "11140", name: "서울특별시 중구", aliases: ["서울 중구"] },
  { code: "11170", name: "서울특별시 용산구", aliases: ["서울 용산구"] },
  { code: "11200", name: "서울특별시 성동구", aliases: ["서울 성동구"] },
  { code: "11215", name: "서울특별시 광진구", aliases: ["서울 광진구"] },
  { code: "11230", name: "서울특별시 동대문구", aliases: ["서울 동대문구"] },
  { code: "11260", name: "서울특별시 중랑구", aliases: ["서울 중랑구"] },
  { code: "11290", name: "서울특별시 성북구", aliases: ["서울 성북구"] },
  { code: "11305", name: "서울특별시 강북구", aliases: ["서울 강북구"] },
  { code: "11320", name: "서울특별시 도봉구", aliases: ["서울 도봉구"] },
  { code: "11350", name: "서울특별시 노원구", aliases: ["서울 노원구"] },
  { code: "11380", name: "서울특별시 은평구", aliases: ["서울 은평구"] },
  { code: "11410", name: "서울특별시 서대문구", aliases: ["서울 서대문구"] },
  { code: "11440", name: "서울특별시 마포구", aliases: ["서울 마포구"] },
  { code: "11470", name: "서울특별시 양천구", aliases: ["서울 양천구"] },
  { code: "11500", name: "서울특별시 강서구", aliases: ["서울 강서구"] },
  { code: "11530", name: "서울특별시 구로구", aliases: ["서울 구로구"] },
  { code: "11545", name: "서울특별시 금천구", aliases: ["서울 금천구"] },
  { code: "11560", name: "서울특별시 영등포구", aliases: ["서울 영등포구"] },
  { code: "11590", name: "서울특별시 동작구", aliases: ["서울 동작구"] },
  { code: "11620", name: "서울특별시 관악구", aliases: ["서울 관악구"] },
  { code: "11650", name: "서울특별시 서초구", aliases: ["서울 서초구"] },
  { code: "11680", name: "서울특별시 강남구", aliases: ["서울 강남구"] },
  { code: "11710", name: "서울특별시 송파구", aliases: ["서울 송파구"] },
  { code: "11740", name: "서울특별시 강동구", aliases: ["서울 강동구"] },
  { code: "26110", name: "부산광역시 중구", aliases: ["부산 중구"] },
  { code: "26140", name: "부산광역시 서구", aliases: ["부산 서구"] },
  { code: "26170", name: "부산광역시 동구", aliases: ["부산 동구"] },
  { code: "26200", name: "부산광역시 영도구", aliases: ["부산 영도구"] },
  { code: "26230", name: "부산광역시 부산진구", aliases: ["부산 부산진구"] },
  { code: "26260", name: "부산광역시 동래구", aliases: ["부산 동래구"] },
  { code: "26290", name: "부산광역시 남구", aliases: ["부산 남구"] },
  { code: "26320", name: "부산광역시 북구", aliases: ["부산 북구"] },
  { code: "26350", name: "부산광역시 해운대구", aliases: ["부산 해운대구"] },
  { code: "26380", name: "부산광역시 사하구", aliases: ["부산 사하구"] },
  { code: "26410", name: "부산광역시 금정구", aliases: ["부산 금정구"] },
  { code: "26440", name: "부산광역시 강서구", aliases: ["부산 강서구"] },
  { code: "26470", name: "부산광역시 연제구", aliases: ["부산 연제구"] },
  { code: "26500", name: "부산광역시 수영구", aliases: ["부산 수영구"] },
  { code: "26530", name: "부산광역시 사상구", aliases: ["부산 사상구"] },
  { code: "26710", name: "부산광역시 기장군", aliases: ["부산 기장군"] },
  { code: "27110", name: "대구광역시 중구", aliases: ["대구 중구"] },
  { code: "27140", name: "대구광역시 동구", aliases: ["대구 동구"] },
  { code: "27170", name: "대구광역시 서구", aliases: ["대구 서구"] },
  { code: "27200", name: "대구광역시 남구", aliases: ["대구 남구"] },
  { code: "27230", name: "대구광역시 북구", aliases: ["대구 북구"] },
  { code: "27260", name: "대구광역시 수성구", aliases: ["대구 수성구"] },
  { code: "27290", name: "대구광역시 달서구", aliases: ["대구 달서구"] },
  { code: "27710", name: "대구광역시 달성군", aliases: ["대구 달성군"] },
  { code: "27720", name: "대구광역시 군위군", aliases: ["대구 군위군"] },
  { code: "28110", name: "인천광역시 중구", aliases: ["인천 중구"] },
  { code: "28140", name: "인천광역시 동구", aliases: ["인천 동구"] },
  { code: "28177", name: "인천광역시 미추홀구", aliases: ["인천 미추홀구"] },
  { code: "28185", name: "인천광역시 연수구", aliases: ["인천 연수구"] },
  { code: "28200", name: "인천광역시 남동구", aliases: ["인천 남동구"] },
  { code: "28237", name: "인천광역시 부평구", aliases: ["인천 부평구"] },
  { code: "28245", name: "인천광역시 계양구", aliases: ["인천 계양구"] },
  { code: "28260", name: "인천광역시 서구", aliases: ["인천 서구"] },
  { code: "28710", name: "인천광역시 강화군", aliases: ["인천 강화군"] },
  { code: "28720", name: "인천광역시 옹진군", aliases: ["인천 옹진군"] },
  { code: "29110", name: "광주광역시 동구", aliases: ["광주 동구"] },
  { code: "29140", name: "광주광역시 서구", aliases: ["광주 서구"] },
  { code: "29155", name: "광주광역시 남구", aliases: ["광주 남구"] },
  { code: "29170", name: "광주광역시 북구", aliases: ["광주 북구"] },
  { code: "29200", name: "광주광역시 광산구", aliases: ["광주 광산구"] },
  { code: "30110", name: "대전광역시 동구", aliases: ["대전 동구"] },
  { code: "30140", name: "대전광역시 중구", aliases: ["대전 중구"] },
  { code: "30170", name: "대전광역시 서구", aliases: ["대전 서구"] },
  { code: "30200", name: "대전광역시 유성구", aliases: ["대전 유성구"] },
  { code: "30230", name: "대전광역시 대덕구", aliases: ["대전 대덕구"] },
  { code: "31110", name: "울산광역시 중구", aliases: ["울산 중구"] },
  { code: "31140", name: "울산광역시 남구", aliases: ["울산 남구"] },
  { code: "31170", name: "울산광역시 동구", aliases: ["울산 동구"] },
  { code: "31200", name: "울산광역시 북구", aliases: ["울산 북구"] },
  { code: "31710", name: "울산광역시 울주군", aliases: ["울산 울주군"] },
  { code: "36110", name: "세종특별자치시", aliases: ["세종시", "세종"] },
  { code: "41111", name: "경기도 수원시 장안구", aliases: ["수원시 장안구", "수원 장안구"] },
  { code: "41113", name: "경기도 수원시 권선구", aliases: ["수원시 권선구", "수원 권선구"] },
  { code: "41115", name: "경기도 수원시 팔달구", aliases: ["수원시 팔달구", "수원 팔달구"] },
  { code: "41117", name: "경기도 수원시 영통구", aliases: ["수원시 영통구", "수원 영통구"] },
  { code: "41131", name: "경기도 성남시 수정구", aliases: ["성남시 수정구", "성남 수정구"] },
  { code: "41133", name: "경기도 성남시 중원구", aliases: ["성남시 중원구", "성남 중원구"] },
  { code: "41135", name: "경기도 성남시 분당구", aliases: ["성남시 분당구", "성남 분당구"] },
  { code: "41150", name: "경기도 의정부시", aliases: ["의정부시", "의정부"] },
  { code: "41171", name: "경기도 안양시 만안구", aliases: ["안양시 만안구", "안양 만안구"] },
  { code: "41173", name: "경기도 안양시 동안구", aliases: ["안양시 동안구", "안양 동안구"] },
  { code: "41192", name: "경기도 부천시 원미구", aliases: ["부천시 원미구", "부천 원미구"] },
  { code: "41194", name: "경기도 부천시 소사구", aliases: ["부천시 소사구", "부천 소사구"] },
  { code: "41196", name: "경기도 부천시 오정구", aliases: ["부천시 오정구", "부천 오정구"] },
  { code: "41210", name: "경기도 광명시", aliases: ["광명시", "광명"] },
  { code: "41220", name: "경기도 평택시", aliases: ["평택시", "평택"] },
  { code: "41250", name: "경기도 동두천시", aliases: ["동두천시", "동두천"] },
  { code: "41271", name: "경기도 안산시 상록구", aliases: ["안산시 상록구", "안산 상록구"] },
  { code: "41273", name: "경기도 안산시 단원구", aliases: ["안산시 단원구", "안산 단원구"] },
  { code: "41281", name: "경기도 고양시 덕양구", aliases: ["고양시 덕양구", "고양 덕양구"] },
  { code: "41285", name: "경기도 고양시 일산동구", aliases: ["고양시 일산동구", "고양 일산동구"] },
  { code: "41287", name: "경기도 고양시 일산서구", aliases: ["고양시 일산서구", "고양 일산서구"] },
  { code: "41290", name: "경기도 과천시", aliases: ["과천시", "과천"] },
  { code: "41310", name: "경기도 구리시", aliases: ["구리시", "구리"] },
  { code: "41360", name: "경기도 남양주시", aliases: ["남양주시", "남양주"] },
  { code: "41370", name: "경기도 오산시", aliases: ["오산시", "오산"] },
  { code: "41390", name: "경기도 시흥시", aliases: ["시흥시", "시흥"] },
  { code: "41410", name: "경기도 군포시", aliases: ["군포시", "군포"] },
  { code: "41430", name: "경기도 의왕시", aliases: ["의왕시", "의왕"] },
  { code: "41450", name: "경기도 하남시", aliases: ["하남시", "하남"] },
  { code: "41461", name: "경기도 용인시 처인구", aliases: ["용인시 처인구", "용인 처인구"] },
  { code: "41463", name: "경기도 용인시 기흥구", aliases: ["용인시 기흥구", "용인 기흥구"] },
  { code: "41465", name: "경기도 용인시 수지구", aliases: ["용인시 수지구", "용인 수지구"] },
  { code: "41480", name: "경기도 파주시", aliases: ["파주시", "파주"] },
  { code: "41500", name: "경기도 이천시", aliases: ["이천시", "이천"] },
  { code: "41550", name: "경기도 안성시", aliases: ["안성시", "안성"] },
  { code: "41570", name: "경기도 김포시", aliases: ["김포시", "김포"] },
  { code: "41590", name: "경기도 화성시", aliases: ["화성시", "화성"] },
  { code: "41610", name: "경기도 광주시", aliases: ["경기 광주시", "경기도 광주"] },
  { code: "41630", name: "경기도 양주시", aliases: ["양주시", "양주"] },
  { code: "41650", name: "경기도 포천시", aliases: ["포천시", "포천"] },
  { code: "41670", name: "경기도 여주시", aliases: ["여주시", "여주"] },
  { code: "41800", name: "경기도 연천군", aliases: ["연천군", "연천"] },
  { code: "41820", name: "경기도 가평군", aliases: ["가평군", "가평"] },
  { code: "41830", name: "경기도 양평군", aliases: ["양평군", "양평"] },
] as const;

function normalized(value: string): string {
  return value.replace(/\s+/g, "").replace(/서울특별시/g, "서울").replace(/부산광역시/g, "부산").replace(/대구광역시/g, "대구").replace(/인천광역시/g, "인천").replace(/광주광역시/g, "광주").replace(/대전광역시/g, "대전").replace(/울산광역시/g, "울산").replace(/세종특별자치시/g, "세종").replace(/경기도/g, "경기");
}

export function resolveRegion(input: string, displayLabel = ""): SupportedRegion | null {
  const haystack = normalized(`${input} ${displayLabel}`);
  const matches = SUPPORTED_REGIONS.filter((region) => [region.name, ...(region.aliases ?? [])].some((name) => haystack.includes(normalized(name))));
  return matches.sort((a, b) => normalized(b.name).length - normalized(a.name).length)[0] ?? null;
}
